### ISSUE TITLE
Failed to compare two elements in the array.

### ISSUE THREAD

**Issue by cemberkongay** [NaturalDocs/NaturalDocs#22]
Generated on 5.04.2018 11:52:29

Crash Message:

   Failed to compare two elements in the array.
   (System.InvalidOperationException)

Caused By:

   Object must be of type String.
   (System.ArgumentException)

Stack Trace:

   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at CodeClear.NaturalDocs.Engine.Errors.ErrorList.get_ConfigFiles()
   at CodeClear.NaturalDocs.Engine.ConfigFile.TryToAnnotateWithErrors(ErrorList errorList)
   at CodeClear.NaturalDocs.CLI.Application.HandleErrorList(ErrorList errorList)
   at CodeClear.NaturalDocs.CLI.Application.Main(String[] commandLine)

Command Line:

   "C:\Program Files (x86)\Natural Docs\NaturalDocs.exe"  C:\Users\\####\Desktop\ND Config --pause-before-exit

Version: 2.0.1
Platform: Microsoft Windows NT 6.2.9200.0 (Win32NT)
SQLite: 3.13.0

**Comment by NaturalDocs** [comment]
This is interesting.  There was a problem in your config files and then the code that annotates them crashed.  Could you post the three .txt files in your ND Config folder?  If you don't want to post them publicly you can [e-mail them to me](http://www.naturaldocs.org/support/).
