### ISSUE TITLE
Failed to compare two elements in the array

### ISSUE THREAD

**Issue by skorotkov-nix** [NaturalDocs/NaturalDocs#49]
Crash Message:

   Failed to compare two elements in the array.
   (System.InvalidOperationException)

Caused By:

   Object must be of type String.
   (System.ArgumentException)

Stack Trace:

   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at CodeClear.NaturalDocs.Engine.Errors.ErrorList.get_ConfigFiles()
   at CodeClear.NaturalDocs.Engine.ConfigFile.TryToAnnotateWithErrors(ErrorList errorList)
   at CodeClear.NaturalDocs.CLI.Application.HandleErrorList(ErrorList errorList)
   at CodeClear.NaturalDocs.CLI.Application.Main(String[] commandLine)

Command Line:

   NaturalDocs.exe  "D:\try\Some\ND Config"  --pause-before-exit

Versions:
[!Languages.txt](https://github.com/NaturalDocs/NaturalDocs/files/5217478/Languages.txt)

   Natural Docs 2.0.2

   .NET 4.8.3928.0
   Microsoft Windows NT 6.2.9200.0 (Win32NT)

   SQLite 3.13.0

**Comment by NaturalDocs** [comment]
This looks like the crash that was fixed in 2.1 Development Release 1.  [Download the latest development release](https://www.naturaldocs.org/download/#Development) and this should be resolved.  It will also be included in 2.1 when that's released.

**Comment by NaturalDocs** [comment]
Looks like I forgot to close this after 2.1 was released.
